name: Test Coverage
on: pull_request
jobs:
    test-coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Jest coverage report
              uses: ArtiomTr/jest-coverage-report-action@v2.1.2
              id: coverage
              with:
                  skip-step: install
                  annotations: all
                  test-script: npx jest --ci --json --coverage --testLocationInResults --outputFile="report.json"
                  output: report-markdown
            - name: Comment on pull request
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  hide_and_recreate: true
                  hide_classify: "OUTDATED"
                  message: ${{ steps.coverage.outputs.report }}
